#server:
#  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  message:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

management:
  endpoint:
    web:
      exposure:
        include: "*"